version: 2.1

executors:
  php71:
    working_directory: '~/project'
    docker:
      - image: 'circleci/php:7.1'

  php72:
    working_directory: '~/project'
    docker:
      - image: 'circleci/php:7.2'

  php73:
    working_directory: '~/project'
    docker:
      - image: 'circleci/php:7.3'

  php74:
    working_directory: '~/project'
    docker:
      - image: 'circleci/php:7.4'

commands:
    php--run-unit-tests:
        steps:
            - attach_workspace:
                at: '.'
            - run:
                name: 'Run unit tests'
                command: 'phpdbg -qrr vendor/bin/phpunit'

            - store_test_results:
                path: '.phpunit/report'

    php--run-static-analysis:
        steps:
            - attach_workspace:
                at: '.'
            - run:
                name: 'Run syntax check'
                command: 'composer lint'
            - run:
                name: 'Run code formatting check'
                command: 'composer sniff'

persist_workspace: &persist_workspace
    persist_to_workspace:
        root: '.'
        paths: [ '.' ]

workflows:

    version: 2

    pipeline:
        jobs:
            - fetch_code

            - php71_install_dependencies:
                requires: [ fetch_code ]
            - php71_testing:
                requires: [ php71_install_dependencies ]

            - php72_install_dependencies:
                requires: [ fetch_code ]
            - php72_testing:
                requires: [ php72_install_dependencies ]

            - php73_install_dependencies:
                requires: [ fetch_code ]
            - php73_testing:
                requires: [ php73_install_dependencies ]

            - fan_in:
                requires:
                    - 'php71_testing'
                    - 'php72_testing'
                    - 'php73_testing'

jobs:

    fan_in:
        executor: 'php71'
        steps: [ { run: 'whoami' } ]

    fetch_code:
        executor: 'php71'
        steps:
            - checkout
            - *persist_workspace

    php71_install_dependencies:
        executor: 'php71'
        steps:
            - attach_workspace:
                at: '.'

            - restore_cache: { keys: [ 'v1-php71-deps-{{ checksum "composer.json" }}', 'v1-php71-deps' ] }

            - run:
                name: 'Install PHP dependencies'
                command: 'composer --no-interaction --no-progress install && composer show'

            - save_cache: { key: 'v1-php71-deps-{{ checksum "composer.json" }}', paths: [ 'vendor' ] }

            - *persist_workspace

    php71_testing:
        executor: 'php71'
        steps:
            - php--run-static-analysis
            - php--run-unit-tests

    php72_install_dependencies:
        executor: 'php72'
        steps:
            - attach_workspace:
                at: '.'

            - restore_cache: { keys: [ 'v1-php72-deps-{{ checksum "composer.json" }}', 'v1-php72-deps' ] }

            - run:
                name: 'Install PHP dependencies'
                command: 'composer --no-interaction --no-progress install && composer show'

            - save_cache: { key: 'v1-php72-deps-{{ checksum "composer.json" }}', paths: [ 'vendor' ] }

            - *persist_workspace

    php72_testing:
        executor: 'php72'
        steps:
            - php--run-static-analysis
            - php--run-unit-tests

    php73_install_dependencies:
        executor: 'php73'
        environment: [ {PHP_VERSION: 'php73'} ]
        steps:
            - attach_workspace:
                at: '.'

            - restore_cache: { keys: [ 'v1-php73-deps-{{ checksum "composer.json" }}', 'v1-php73-deps' ] }

            - run:
                name: 'Install PHP dependencies'
                command: 'composer --no-interaction --no-progress install && composer show'

            - save_cache: { key: 'v1-php73-deps-{{ checksum "composer.json" }}', paths: [ 'vendor' ] }

            - *persist_workspace

    php73_testing:
        executor: 'php73'
        steps:
            - php--run-static-analysis
            - php--run-unit-tests
